baseURL = 'https://stdout.oliverfischer.dev'
defaultContentLanguage = "de"
languageCode = "de-DE"
theme = 'hugo-coder'
title = 'stdout'
publishDir = "generated-site"
staticDir = "static-content"

[menu]
    [[menu.main]]
        name = "Home"
        pageRef = "/"
        weight = 10

        [[menu.main]]
        name = "Posts"
        pageRef = "/posts"
        weight = 20

        [[menu.main]]
        name = "Knowledge Hub"
        url = "https://best-practices.oliverfischer.dev/"
        weight = 20

        [[menu.main]]
        name = "Impressum"
        pageRef = "/impressum/"
        weight = 100

        [[menu.main]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/oliverfischer/"
        weight = 30

        [[menu.main]]
        name = "Linktree"
        url = "https://linktr.ee/oliver.fischer"
        weight = 35

[markup]
    [markup.asciidocExt]
        noHeaderOrFooter = true
        preserveTOC = false
        backend = 'html5'

        extensions = ['asciidoctor-diagram']
        workingFolderCurrent = true

    [markup.asciidocExt.attributes]
        "showtitle!" = "" # Deaktiviert die Anzeige der obersten Überschrift
        figure-caption = "Abbildung"
        listing-caption = "Listing"
        rouge-style = 'tulip'
        rouge-css = 'style'
        source-highlighter = 'rouge'
        stem = 'latexmath'
        mmdc = "./node_modules/.bin/mmdc"

[params]
    author = "Oliver B. Fischer"
    dateFormat = "2. January 2006"
    description = "Oliver Fischers Blog zu Dingen rund um IT und Sofwareentwicklung"
    favicon_16 = "favicon-16x16.png"
    favicon_32 = "favicon-32x32.png"
    faviconSVG = "favicon.svg"
    touchicon = "apple-touch-icon.png"
    gravatar = "hallo@oliverfischer.dev"
    hideColorSchemeToggle = true
    manifest = "site.webmanifest"
    since = 2025
    customCSS = ["customization.css"]
    info = [
        "Digital Product Architect",
        "Ich helfe mittelständischen Unternehmen und Organisationen aus einer Geschäftsidee ein funktionierendes digitales Produkt zu machen – von der Konzeption über die technische Umsetzung bis zum Betrieb."
        ]

[frontmatter]
    title = [":title", ":doctitle"]
    lastmod = [":modified", ":lastmod"]
    publishDate = [":publishDate", ":date"]

[security]
    [security.exec]
        allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
