+++ 
draft = true
date = "2025-11-29T14:40:29+01:00"
title = "Ein universelles Schema für Git-Branching"
description = "d"
keywords = ["git", "branching", "source code control", "workflow"]
slug = "aaaaaaaaaaaaaaaaaaaaaaa"
categories = ['Tidy First', 'Git']
+++

= Weitere Namensräume für Branches in Git-Projekten

Ein effektives Branching-Schema ist ein wichtiger Baustein für eine erfolgreiche Git-Nutzung in jedem Projekt und geht über die Benennung des Haupt-Branches und der für Features und Bugfixes hinaus. Warum nur `main` und das Triptychon aus `feature/+*+`, `improvement/+*+` und `bugfix/+*+` nicht ausreicht und wie es vielleicht besser geht, zeige ich hier.
Los geht`s!

== Die Motivation

Im Jahre 2010 hat Vincent Driessen in seinem Blog im Artikel _https://nvie.com/posts/a-successful-git-branching-model[A successful Git branching model]_ das Git-Flow-Model beschrieben.
Das Git-Flow-Model stellt Organisationen einen einheitlichen Vorschlag für die Arbeit an einen Software-Projekt bereit, um Software-Projekte mit unterschiedlichen Release-Versionen über deren gesamten Lifecyle entwickeln zu können.
Der Titel seines Blog-Artikels stellt eine selbsterfüllende Prophezeiung dar, denn das für ihn erfolgreiche Branching-Modell wurde so populär, dass auch darüber hinaus seinen Siegeszug angetreten hat.

Vorab sollte an dieser Stelle gesagt sein, dass das Git-Flow-Model effizient und effektiv ist und in seiner Form ausgezeichnet für viele Projekte funktioniert.

Mit Git-Flow führt Driessen auch die folgenden Präfixe für Branch-Namen ein:

* `feature/+*+` für Branches auf denen neue Funktionen entwickelt werden
* `release/+*+` für Releases
* `hotfix/+*+` für dringende Fehlerbehebungen

Der auch oft gesehen Branch-Namenspräfix `improvement/+*+` existiert bei Vincent Driessen 2010 noch nicht, taucht aber in den folgenden Jahren in der Git-Community auf.

Übergreifend haben sich in den folgenden Jahren die folgenden drei Präfixe für Git-Branch-Namen etabliert:

* `feature/+*+` für neue Funktionen
* `improvement/+*+` für kleine Änderungen, die keine neuen Funktionen an sich bereitstellen
* `bugfix/+*+` für reine Fehlerbehebungen

`feature`, `improvement` und `bugfix` sind Namensräume, in die wir unsere Arbeit einsortieren können, um anderen es leichter zu machen sie zu erkennen.

In meiner Praxis konnte ich aber auch immer folgende drei Phänomene beobachten, die alle zu einer schlechteren Übersichtlichkeit und damit zu mehr Mental Load geführt haben:

1. Alte und verwaiste Branches ohne Aktivität
2. Private Branches, auf denen Teammitglieder experimentiert haben
3. Archivbranches, welche aus unterschiedlichen Gründen aufgehoben werden

Die Abgrenzung zwischen diesen Drein ist fließend, gemein ist ihnen jedoch, dass sie die für uns notwendigen Namensräume verschmutzen und uns es erschwert, Relevantes von irrelevantem zu unterscheiden.



== Erweiterung des Git-Flow-Schema-Branching-Schema

Auf wen die drei beschriebenen Phänonmene zutreffen, sollte erwägen sein Branching-Schema um die Namensräume und Präfixe `private` und `archiv` zu erweitern.

* `private/<name>` für jeden Branch mit Ideen und Arbeiten von Teammitgliedern ohne direkten Bezug zu anderen Aufgaben und Teammitgliedern, wobei der Name des einzelnen Teammitglieds dem Branchname als weiteres Separationselement hinzugefügt wird
* `archive` für Branches, die nicht aktiv benötigt, aber auch nicht gelöscht werden wollen


== Wegwerfen kommt vor dem Aufräumen

Bevor die hier vorgestellte Erweiterung des Branching-Schemas erwogen wird, sollte zuerst aufgeräumt werden.
Im ersten Schritt muss die Einhaltung des Standard-Triptychons aus `feature`, `bugfix` und `improvement` umgesetzt werden.
Hier sollten sich anschließend nur Branches benfinden, auf denen eine aktiv gearbeitet wird und die eine reelle Chance haben in die aktive Hauptentwicklungslinie eingebracht zu werden.
Damit ist dann die Grundlage geschaffen, um im nächsten Schritt nicht benötigte Branches zu löschen.
Bleiben am Ende Branches übrig, auf denen weder aktiv gearbeitet wird, noch die gelöscht werden können, sollten diese nach `private` oder `archiv` verschoben werden.


== Fazit und Ausblick

In diesem Post habe ich eine Erweiterung des etablierten Branching-Schemas von Git-Flow vorgestellt, mit der eine bessere Übersichtlichkeit erreicht werden kann, falls das etablierte Schema sich als nicht ausreichend erweist, um mit geringem mentalem Aufwand einen Überblick über die Arbeit in einem Git-Repository zu erhalten.

Vor der Umsetzung der Erweitung sollte zuerst geprüft werden, ob diese überhaupt notwendig ist oder durch die Beendigung von Arbeiten und dem Aussortieren von nicht mehr benötigten Branches das gleiche Ergebnis erreicht werden kann.

== Quellen und Verweise

* https://nvie.com/posts/a-successful-git-branching-model/[A successful Git branching model, Vincent Driessen, 2010]
